#
# Configuration for travis-ci testing
# This tests ubuntu by default, but can also be made to test on osx
#
sudo: false

# Test on Ubuntu 14
dist: trusty

language: python

env:
  - OXRSE_UNIT=false
    OXRSE_COVER=false
    OXRSE_STYLE=false
    OXRSE_DOCS=false


matrix:
    # Always put true env variable first, for nicer overview on travis website
    include:
        # Unit tests on different python versions
        - python: "2.7"
          env:
            - OXRSE_UNIT=true
        - python: "3.4"
          env:
            - OXRSE_UNIT=true
        - python: "3.5"
          env:
            - OXRSE_UNIT=true
        - python: "3.6"
          env:
            - OXRSE_UNIT=true

        # Cover, style, and docs (latest version only)
        - python: "3.6"
          env:
            - OXRSE_COVER=true
        - python: "3.6"
          env:
            - OXRSE_STYLE=true
        #- python: "3.6"
        #  env:
            - OXRSE_DOCS=true

# Install Python dependencies
install:
  # Install OxRSE with extra dependencies
  - pip install -e .[dev,docs]
  # Install cover checking libraries
  - if [[ $OXRSE_COVER == true ]]; then pip install coverage codecov; fi;

# Show Python version
before_script:
- python --version

# Run tests
script:
  - if [[ $OXRSE_UNIT == true ]]; then python -m unittest discover; fi;
  - if [[ $OXRSE_COVER == true ]]; then coverage run python -m unittest discover; fi;
  - if [[ $OXRSE_STYLE == true ]]; then python -m flake8; fi;
  - if [[ $OXRSE_DOCS == true ]]; then sphinx-build -b html docs/source docs/build/html -W; fi;

# Compile coverage report
after_success:
  - if [[ $MYOKIT_COVER == true ]]; then codecov; fi;

# Send notifications
notifications:
  email:
    recipients:
    - michael.clerx@cs.ox.ac.uk

